# See smb.conf.example for a more detailed config file or
# read the smb.conf manpage.
# Run 'testparm' to verify the config is correct after
# you modified it.
#
# Note:
# SMB1 is disabled by default. This means clients without support for SMB2 or
# SMB3 are no longer able to connect to smbd (by default).

[global]
	force create mode = 777
	printcap name = cups
	min protocol = SMB2
	workgroup = [ NETWORK NAME ]
	;interfaces = 192.168.12.2/24 192.168.13.2/24
	os level = 20
	wins support = true
	netbios name = [ PC NAME ]
	printing = cups
	log file = /var/log/samba/log.%m
	allow insecure wide links = yes
	create mode = 777
	follow symlinks = yes
	delete readonly = yes
	map to guest = bad user
	max log size = 1000
	load printers = yes
	force directory mode = 777
	cups options = raw
	security = user
	logging = file
	directory mode = 777
	auto services = global
	guest account = nobody
    
#[printers]
#	comment = All Printers
#	path = /var/tmp
#	printable = Yes
#	create mask = 0600
#	browseable = No

#[print$]
#	comment = Printer Drivers
#	path = /var/lib/samba/drivers
#	write list = @printadmin root
#	force group = @printadmin
#	create mask = 0664
#	directory mask = 0775

[NAME]
 path = /path/to/share
 browseable = yes
 guest ok = yes
 read only = no
 public = yes
 follow symlinks = yes
 wide links = yes
 ;printable = yes
 



